Adriandmen/05AB1E

05AB1E.py, lib/encoding.py
When the -c/--osabie flag was passed, the interpreter was previously
reading the input file as UTF-8 anyway. Since the 05AB1E codepage
contains bytes that are invalid UTF-8, this fails for many programs.
Instead, it should read the file in binary mode rather than interpreting
what should be raw bytes under any kind of encoding.
=> Read 05AB1E-encoded files as raw bytes, not UTF-8

.gitignore, lib/commands.py, osabie.py, test/unit_tests/arithmetic.tests
As I mentioned in #72, I'm new to the idioms of 05AB1E, but hopefully the tests are adequate.
My python is also quite rusty, so please do critique anything about the implementation.
Additionally, I noticed two files left behind after failed test runs; I added them to `.gitignore`.
=> Implement `.Ø` index-of-prime operator and tests

osabie.py
Fix `list index out of range` exceptions thrown when 05AB1E tries to implicitly fetch from a non-existent input.
This is done by catching that exception and returning an empty string, which seems to be the best possible approximation of an empty input.
```
$ wc -c ~/tmp/sandbox/inputs
0 /home/scottinet/tmp/sandbox/inputs
$ python3 osabie.py -d ~/tmp/sandbox/golf.abe < ~/tmp/sandbox/inputs 
Full program: 0«{γε¨g4÷¼}O¾<+3›
current >> 0  ||  stack: []
current >> «  ||  stack: ['0']
list index out of range
current >> {  ||  stack: []
list index out of range
...<snip>
```
https://codegolf.stackexchange.com/questions/141581/can-i-settle-down/141660#141660
=> Fix index errors from empty inputs

docs/md-documentation/loops.md, osabie.py, test/unit_tests/advanced.tests
Motivated by [this challenge](https://codegolf.stackexchange.com/questions/141949/count-edits-accounting-for-grace-period) I attempted this morning. I had a 12 bytes answer, tying with Jelly, but it didn't work as expected due to the bugs fixed in this PR :)
This PR fixes several problems with block statement extractions, by removing all specific block-detecting code in each command, using a unique `get_block_statement` to do the job. This should prevent inconsistencies across block commands due to different implementations, namely:
* `µ` and `ε` weren't considered as blocks by other block commands, causing parsing problems
Example: https://tio.run/##MzBNTDJM/f/f2M3E59xWP@1aFx0/nf///@umAAA
* #80
Example: https://tio.run/##MzBNTDJM/f//1KSyysMdtf61Ov//R0cb6CgY6igY6SgYx@ooREOZIF4sAA
This …
=> Fix nested blocks detection

docs/info.txt, osabie.py, test/unit_tests/advanced.tests, test/unit_tests/loops.tests
Change the behavior of `]` from "close an infinite loop" to "close all loops and if statements"
Infinite loops (`[`) can now be closed normally, either with `}`, `]`, or implicitly if at the end of a program.
Updated the documentation and added a test case
Related issue and discussion: #95
=> Make ']' an infinite close command

lib/commands/str_commands.ex, test/commands/ternary_test.exs
As [Kevin Cruijssen pointed out](https://chat.stackexchange.com/transcript/message/46778324#46778324), transliteration does not work properly when one of the parameters is an integer. This is now fixed by replacing `is_bitstring` with `is_single?` (which checks whether an element is a string or number) and always casts to a string if this is the case.
Tests are now also [added](https://github.com/Adriandmen/05AB1E/blob/209202cc318dd9f06d7241a2cabaf6c959672431/test/commands/ternary_test.exs#L14) to make sure that this does not happen again.
=> Fix transliteration bug

lib/commands/list_commands.ex, test/commands/binary_test.exs
Retrieving the index of a string with a length larger than 1 [always results in -1](https://chat.stackexchange.com/transcript/message/46506319#46506319). This is now fixed by using the `:binary.match` method which retrieves can also retrieve the index of a multi-character string in a string.
Tests have been [added](https://github.com/Adriandmen/05AB1E/blob/b7269b9caeefec99d83f242efd9cd5bf257e50be/test/commands/binary_test.exs#L320) as well.
=> Fix index of multi-character strings in string

lib/commands/int_commands.ex, lib/commands/list_commands.ex, lib/interp/functions.ex, lib/interp/interpreter.ex, test/commands/binary_test.exs, test/commands/ternary_test.exs, test/commands/unary_test.exs
From [this chat message](https://chat.stackexchange.com/transcript/message/46500066#46500066).
Some commands that only can use integers (and not floats) are now implicitly casting the values to integers (floor rounding). Most likely, there are some commands that still have this problem but the ones currently resolved (or are already resolved) are:
- `L`
- `b`
- `h`
- `±`
- `Ý`
- `ç`
- `Ò`
- `f`
- `Ó`
- `Ñ`
- `Ø`
- `Å0`
- `Å1`
- `Å2`
- `Å3`
- `Å4`
- `Å5`
- `Å6`
- `Å7`
- `Å8`
- `Å9`
- `.X`
- `Åœ`
- `ô`
- `ä`
- `∍`
- `ú`
- `è`
- `~`
- `B`
- `^`
- `&`
- `£`
- `c`
- `e`
- `Ÿ`
- `ù`
- `ι`
- `ã`
- `в`
- `ö`
- `.£`
- `.D`
- `.ò`
- `j`
- `.$`
- `.Æ`
- `.Œ`
- `._`
- `ÅΓ`
- `.I`
- `ǝ`
- `Λ`
- `.Λ`
- `F`
- `E`
- `G`
- `ƒ`
- `µ`
=> Fix int conversion

lib/interp/interpreter.ex, test/commands/special_test.exs
Until now, `ƒ` and `E` were exact synonyms, as [pointed out by Kevin Cruijssen](https://chat.stackexchange.com/transcript/message/46839878#46839878). `E` should have been **[1, n]** (or **(0, n]**) in the first place, not **[0, n]**, which is already covered by the other aforementioned command.
=> Fixed the E-loop

lib/interp/interpreter.ex, test/commands/special_test.exs
The sort by function breaks when sorting unevaluated elements with each other (e.g. streams). Values are now evaluated when transformed:
https://github.com/Adriandmen/05AB1E/blob/a3b67f6bcf871e7212c06452158a0706ce236c03/lib/interp/interpreter.ex#L657-L664
Added the example [Emigna gave](https://chat.stackexchange.com/transcript/message/46919028#46919028) as an additional test:
https://github.com/Adriandmen/05AB1E/blob/a3b67f6bcf871e7212c06452158a0706ce236c03/test/commands/special_test.exs#L56
=> Fix sort by

lib/interp/interpreter.ex, lib/osabie.ex
As Emigna [pointed out](https://chat.stackexchange.com/transcript/message/47023139#47023139), stack rotation throws exceptions because the rotated version of the stack is not casted explicitly to a list. This is now done using the `Enum.to_list` function.
=> Fix stack rotation

lib/interp/interpreter.ex
Unmatched brackets like `}` did not return a stack and environment variable which makes the interpreter run into an error. Invalid tokens just return the stack and environment variable and leave them untouched.
=> Fix no op bugs

lib/commands/list_commands.ex, test/commands/binary_test.exs
Indexing of substrings in strings containing Unicode strings did not work properly, because the codepoints of the characters were considered rather than the actual graphemes. This is now fixed by replacing the `:binary.match/2` method with the `String.split/3` method.
=> Fix indexing in Unicode strings

lib/commands/list_commands.ex, test/commands/binary_test.exs
When taking 0 elements from a string or list (using the `£` command), the interpreter would error and return the left argument. Now, these edge cases are added in the `take_first` function:
https://github.com/Adriandmen/05AB1E/blob/7d992e98547e17af237a6565e8b4e3e3c9225070/lib/commands/list_commands.ex#L67-L75
=> Fix take first bug when taking 0 elements

lib/interp/interpreter.ex, test/commands/binary_test.exs
Previously, when performing list multiplication, decimal numbers were not converted to integers which made the command run into a invalid type error. For example:
[1, 2, 3] 3.0 и
This should give `[1, 2, 3, 1, 2, 3, 1, 2, 3]`, but runs into an exception. Fixed by replacing `to_number` with `to_integer`:
https://github.com/Adriandmen/05AB1E/blob/4987160f840c6750db882badcabfe84cdd33a019/lib/interp/interpreter.ex#L344
=> Fix decimal argument to integer parsing bug in list multiplication

docs/info.txt, lib/interp/interpreter.ex, test/commands/constants_test.exs
Adds the code page as the constant `žĆ`. [Requested by @Emigna](https://chat.stackexchange.com/transcript/message/47707085#47707085).
=> Add code page constant

lib/interp/commands/subprogram_interp.ex, test/commands/special_test.exs
Adds the 'first n'-flag as `£` for the recursive list generation command. Usage:
5 1λ£+
Which acts the same as `5 1λ+}s£`.
=> Add 'first n'-flag for the recursive list generation command

lib/commands/int_commands.ex, test/commands/binary_test.exs
Converting negative numbers did not work properly, e.g. `11( 12B`  should result in `-B`.
Fixed by concatenating a `-` before the result of converting the positive number to that base.
=> Fix the negative number to base conversion bug

lib/commands/list_commands.ex, test/commands/binary_test.exs
Fixes the 'take-first'-bug (`£`) on iterables with negative values.
=> Fix take first bug with negative integers on iterable values

lib/commands/gen_commands.ex
As noted by KevinCruijssen, the **run-while** command (`Δ`) sometimes runs into an infinite loop. This was caused by the fact that this command did not use the overridden 'equals'-method (`GeneralCommands.equal/2`):
https://github.com/Adriandmen/05AB1E/blob/fc411e5ae9c73db4030cd47deb37ebd429299e32/lib/commands/gen_commands.ex#L177-L178
=> Fix run while bug

lib/interp/commands/subprogram_interp.ex, test/commands/special_test.exs
Added the `è` flag to `λ`, which given **n**, retrieves the **n**-th element, 0-indexed (such that the behaviour matches that of `e` as a command).
We [have discussed](https://chat.stackexchange.com/transcript/message/46253555#46253555) about adding this flag a while ago but I think the idea has been forgotten since. 
<s>To-do: add tests.</s>
=> New flag – infinite list generation (n-th element)

.gitignore, lib/commands/int_commands.ex, lib/interp/functions.ex, mix.exs, test/commands/binary_test.exs, test/commands/unary_test.exs
Since Elixir and Erlang do not supply their own implementation to support arbitrary precision with the `:math.pow/2` function, we implemented our own _pow_ method that handles arbitrary precision. However, when using floating point numbers, this may result in an infinite loop – most likely caused by the following line of code:
https://github.com/Adriandmen/05AB1E/blob/5ae97149e3e4758e39d351728ce013fd53f2f3c1/lib/commands/int_commands.ex#L81
This has now been fixed by including **0** as well to the range:
https://github.com/Adriandmen/05AB1E/blob/bb62507722e68af12123cf09d9a3ad7dda4721bd/lib/commands/int_commands.ex#L83
A failsafe check has been added as well before entering the recursive pow computation:
https://github.com/Adriandmen/05AB1E/blob/bb62507722e68af12123cf09d9a3ad7dda4721bd/lib/ …
=> Fix the pow function when using floating point numbers

lib/commands/gen_commands.ex, test/commands/binary_test.exs, test/commands/unary_test.exs, test/test_helper.exs
Occasionally when a list is indexed, the list gets cycled and indexed afterward when the index surpasses the length of the list. This however ends up in an infinite cycle when the list is empty. To fix this, a simple check whether the list is empty or not is added.
=> Fix the infinite cycling bug when indexing on an empty list

lib/interp/commands/unary_interp.ex, lib/interp/functions.ex, test/commands/unary_test.exs
The 'is-integer' command (aka `.ï`) checks whether a number can be represented as an integer. The baseline rule to know when a number **_`n`_** is an integer in 05AB1E is when <code><b><i>n</i></b> mod 1 ≡ 0</code>. For example, the following values should return true:
- `4`
- `"4"`
- `4.0`
- `"4.0"`
And the following should return false:
- `4.3`
- `"4.3"`
- `"a"`
This is now performed by checking when:
```
to_number(value) == to_integer(value) and not(is_bitstring(to_number(value)))
```
=> Fix the 'is-integer' command

lib/commands/list_commands.ex, test/commands/special_test.exs
- highly inefficient when done repeatedly, Resolves #185
=> Don't rotate lazily
